### ISSUE TITLE
[computermanagementdsc] noop resource metaparameter is not honoured

### ISSUE THREAD

**Issue by elainemccloskey** [puppetlabs/Puppet.Dsc#222]
See internal JIRA for more info, reference MODULES-11343

**Comment by chelnak** [comment]
Fixed in [this pr](https://github.com/puppetlabs/ruby-pwsh/pull/192)

However, modules will need to be re-published to benefit from the fix

**Comment by ShawnHardwick** [comment]
Thanks. Is there a method for forcing a manual re-publish of the modules?

**Comment by chelnak** [comment]
@ShawnHardwick There sure is. I'm going to get this one out asap while we rework the publish flow.

**Comment by ShawnHardwick** [comment]
@chelnak Has there been an update on this? I still see version 8.5.0-0-0 in the Puppet forge for ComputerManagementDSC
https://forge.puppet.com/modules/dsc/computermanagementdsc

**Comment by chelnak** [comment]
Hey, I will hopefully get updates pushed by the end of the month.

As a temporary resolution you can build the module with the latest version of Puppet.Dsc.. appreciate that might not fit in to your workflow though.

**Comment by ShawnHardwick** [comment]
Looks like the modules were updated on the Puppet Forge. Thanks!

**Comment by chelnak** [comment]
Apologies that it took so long. We should be able to react faster going forward.

Have a fantastic weekend!

**Comment by ShawnHardwick** [comment]
@chelnak My team is migrating our dsc_lite resources in Puppet to Puppet DSC so I've been evaluating the modules we need to import into our Puppetfile. I've noticed that WebAdministrationDSC has also not been updated with the noop fix as it was last updated Sept 17, 2022.

https://forge.puppet.com/modules/dsc/webadministrationdsc

My previously comment was checking a few modules, but it appears that not all modules in the forge were updated?

**Comment by chelnak** [comment]
Hey @ShawnHardwick ,

Your observation is correct, only a handful of modules were updated. At the moment this is intentional. I actually thought that webadministrationdsc was included but I must have missed it.

I can get a new release cut for you asap and for any others that you want re-publishing it would be awesome if you could open new GitHub issues.

**Comment by ShawnHardwick** [comment]
> Hey @ShawnHardwick ,
> 
> Your observation is correct, only a handful of modules were updated. At the moment this is intentional. I actually thought that webadministrationdsc was included but I must have missed it.
> 
> I can get a new release cut for you asap and for any others that you want re-publishing it would be awesome if you could open new GitHub issues.

I appreciate the fast response.  I assumed that all modules were impacted by this PR so any modules that have not been updated since the code change would require a republish. I will submit an issue for future re-publishes. I just felt like the current re-publishes were relevant to this change to get it deployed.

**Comment by chelnak** [comment]
You are right - the noop change will most probably impact most modules.. though while we work on some process stuff in the background we are reducing the scope of what we touch.

Saying that though we always happy to help where we can and if you find something that you need just let us know.

Im hopeful that there will be a bit more movement in this space in 2023 🙂
